version: 3.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: ahteshamahmad/linux_machine
    steps:
      - run: echo "Hi! This is my first runner"
